### ISSUE TITLE
On error, exit 1

### ISSUE THREAD

**Issue by notfed** [itchyny/git-branch-name#1]
Thanks for this project. I'm using it to speed up zsh prompts. 

But, please exit 1 when not in a git repository:

```
if (get_git_dir(path) < 0) {
    return 0;
}
```

...should be...

```
if (get_git_dir(path) < 0) {
    return 1;
}
```

This makes it slightly easier to use from shell scripts.

**Comment by itchyny** [comment]
I'm wondering why bd6b8dedee010654a8b6710fa02989d84c88b6f9 changed the behavior. There must be some problem if it exits with 1. But I forget it.
